<?php


namespace Laragento\Cms\Tests;

use Illuminate\Foundation\Testing\WithFaker;
use Modules\LaragentoAdmin\Models\AdminUser;
use Modules\LaragentoAdmin\Repositories\AdminUserRepository;
use Tests\TestCase;

class CmsTestCase extends TestCase
{
    use WithFaker;
    /**
     * @var $admin AdminUser
     */
    protected $admin;

    /**
     * @var $adminRepo AdminUserRepository
     */
    protected $adminRepo;

    protected function setUp()
    {
        parent::setUp();
        $this->adminRepo = app()->make(AdminUserRepository::class);
        $this->admin = $this->adminRepo->all()->first();
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}